spring:
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: YOUR_API_KEY
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

server:
  port: 8889